pt1:  
Create a one-dimensional tensor in both TensorFlow and PyTorch that contains the values of your interest. Print the tensor to the console for each framework.  
Create a two-dimensional tensor in both TensorFlow and PyTorch that contains the values of your interest. Print the tensor to the console for each framework.  
Create a three-dimensional tensor in both TensorFlow and PyTorch that contains the values of your interest. Print the tensor to the console for each framework.  
Create a function in both TensorFlow and PyTorch that takes two tensors as input and returns the sum of their elements. Test the function with 1D, 2D, and 3D tensors. This function will demonstrate how to perform element-wise addition between two tensors and then sum all elements of the resulting tensor.  

In [3]:
import torch as t
import tensorflow as tf

In [14]:
# one dimensional tensor 
print("pytorch tensor: 1D")
torch_tensor1 = t.tensor([1, 2, 3, 4, 5])
print(torch_tensor1)

print("tensorflow tensor: 1D")
tf_tensor1 = tf.constant([1, 2, 3, 4, 5])
print(tf_tensor1)

# two dimensional tensor
print("\npytorch tensor: 2D")
torch_tensor2 = t.tensor([[1, 2, 3], [4, 5, 6]])
print(torch_tensor2)

print("tensorflow tensor: 2D")
tf_tensor2 = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tf_tensor2)

# three dimensional tensor
print("\npytorch tensor: 3D")
torch_tensor3 = t.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(torch_tensor3)

print("tensorflow tensor: 3D")
tf_tensor3 = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tf_tensor3)


pytorch tensor: 1D
tensor([1, 2, 3, 4, 5])
tensorflow tensor: 1D
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

pytorch tensor: 2D
tensor([[1, 2, 3],
        [4, 5, 6]])
tensorflow tensor: 2D
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

pytorch tensor: 3D
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensorflow tensor: 3D
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [47]:
def sum_tensors(tensor1, tensor2):
    if isinstance(tensor1, (t.Tensor)):
        print("pytorch sum")
        sum = t.add(tensor1, tensor2)
    elif isinstance(tensor1, (tf.Tensor)):
        print("tensorflow sum")
        sum = tf.add(tensor1, tensor2)
    else:
        print("Tensor type not found simply adding tensors, found type: ", type(tensor1))
        sum = tensor1 + tensor2
    print(sum)
    return sum
 

In [48]:
sum_tensor = sum_tensors(torch_tensor1, torch_tensor1)
sum_tensor = sum_tensors(tf_tensor1, tf_tensor1)
print('\n')
sum_tensor = sum_tensors(torch_tensor2, torch_tensor2)
sum_tensor = sum_tensors(tf_tensor2, tf_tensor2)
print('\n')
sum_tensor = sum_tensors(torch_tensor3, torch_tensor3)
sum_tensor = sum_tensors(tf_tensor3, tf_tensor3)

pytorch sum
tensor([ 2,  4,  6,  8, 10])
tensorflow sum
tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32)


pytorch sum
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensorflow sum
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


pytorch sum
tensor([[[ 2,  4],
         [ 6,  8]],

        [[10, 12],
         [14, 16]]])
tensorflow sum
tf.Tensor(
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]], shape=(2, 2, 2), dtype=int32)


pt2:
Broadcasting is a powerful mechanism that allows TensorFlow and PyTorch to work with tensors of different shapes during arithmetic operations. Describe how broadcasting works in tensor operations, providing a simple example to illustrate your explanation.  
Discuss why broadcasting is important and how it enhances the flexibility of tensor operations in building neural network models.  
Explain what limitations or challenges might arise when relying on broadcasting, particularly in the context of ensuring model correctness and efficiency.  


When dealing with tensor operations, if tensor shapes are not the same and ranks are different then we have to transform them into compatible shapes. By making them in the compatible shape broadcasting can be easily applied to perform the tasks. It does this by stretching the smaller tensor to match the shape of the larger tensor. This is done by replicating the smaller tensor along the missing dimensions.  
This is particularly useful in neural network models, due to it's ability to automatically and efficiently handle operations between tensors of different shapes. This allows for more flexibility in the design of neural network models, as it simplifies the process of performing element-wise operations without the need for manually matching array shapes.  
Some limitations that broadcasting introduces are that it can sometimes lead to unexpected results if the user is not careful. This can be due to the fact that broadcasting can automatically adjust tensor shapes, which may lead to unintended results if the user is not aware of how broadcasting works. Additionally, broadcasting can sometimes lead to inefficiencies in terms of memory usage, as it may require additional memory to store the broadcasted tensor. Therefore, it is important to be aware of the limitations of broadcasting and to use it judiciously to ensure model correctness and efficiency.

In [53]:
#Adding new axis to T2 by .expand_dims() at its trailing end
broadcasted_T3 = tf.expand_dims(tf_tensor3, axis=-1)

# arithmetic operation
sum = broadcasted_T3+ tf_tensor2
print(sum)

tf.Tensor(
[[[[ 2  3  4]
   [ 6  7  8]]

  [[ 4  5  6]
   [ 8  9 10]]]


 [[[ 6  7  8]
   [10 11 12]]

  [[ 8  9 10]
   [12 13 14]]]], shape=(2, 2, 2, 3), dtype=int32)
